### ISSUE TITLE
AvailableIPPool的bug，选用备用池时候有异常

### ISSUE THREAD

**Issue by hadrianl** [rainx/pytdx#171]
Traceback (most recent call last):
  File "D:/future_download/FutureData_DailyDownload.py", line 178, in <module>
    data_fetcher.update_1min_data()
  File "D:/future_download/FutureData_DailyDownload.py", line 82, in update_1min_data
    _all_dominant = self.get_all_dominant()
  File "D:/future_download/FutureData_DailyDownload.py", line 145, in get_all_dominant
    ret = self._exapi.do_hq_api_call('get_instrument_quote_list', md, 3, start=i, count=80)
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\pytdx\pool\hqpool.py", line 97, in do_hq_api_call
    self.hot_failover_api.connect(*choise_ip)
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\pytdx\base_socket_client.py", line 160, in connect
    log.debug("connecting to server : %s on port :%d" % (ip, port))
TypeError: %d format: a number is required, not tuple

AvailableIPPool：

    def get_ips(self):
        if not self.sorted_ips:
            return self.ips
        else:
            return list(self.sorted_ips.items()) 

这里最后的一行的返回讲道理应该是 return list(self.sorted_ips.values())

**Comment by hadrianl** [comment]
突然发现这个bug其实已经修复过了，为什么我也是更新到了1.67这个bug还是存在的呢。。。。

**Comment by yutiansut** [comment]
因为你装了tushare

**Comment by yutiansut** [comment]
看下这个
https://github.com/QUANTAXIS/QUANTAXIS/issues/747
