### ISSUE TITLE
怎么获取行情服务器的IP

### ISSUE THREAD

**Issue by Iseuwei** [rainx/pytdx#246]
log.info("查询代码列表")
    api = TdxExHq_API(auto_retry=True)
    with api.connect('119.147.212.81', 7709):
        data = api.get_security_bars(9, 0, '000001', 0, 10)  # 返回普通list
        print(data)

这里的IP怎么获取呢？运行报错：
Traceback (most recent call last):
  File "E:/Iseuwei/WorkSpace/Stock/pytdx-master/pytdx-master/tests/test.py", line 131, in <module>
    test1()
  File "E:/Iseuwei/WorkSpace/Stock/pytdx-master/pytdx-master/tests/test.py", line 119, in test1
    with api.connect('39.100.68.59', 7709):
  File "E:\Iseuwei\WorkSpace\Stock\pytdx-master\pytdx-master\pytdx\base_socket_client.py", line 189, in connect
    self.setup()
  File "E:\Iseuwei\WorkSpace\Stock\pytdx-master\pytdx-master\pytdx\exhq.py", line 59, in setup
    ExSetupCmd1(self.client).call_api()
  File "E:\Iseuwei\WorkSpace\Stock\pytdx-master\pytdx-master\pytdx\parser\base.py", line 74, in call_api
    result = self._call_api()
  File "E:\Iseuwei\WorkSpace\Stock\pytdx-master\pytdx-master\pytdx\parser\base.py", line 102, in _call_api
    head_buf = self.client.recv(self.rsp_header_len)
socket.timeout: timed out

**Comment by Iseuwei** [comment]
已解决谢谢，是我搞错了
