### ISSUE TITLE
api.get_k_data查询沪市股票会错

### ISSUE THREAD

**Issue by cafecai** [rainx/pytdx#58]
查询深市股票正常，当查询沪市股票时会出错，api.get_k_data('600031', '2017-09-14', '2017-09-15')
Traceback (most recent call last):
  File "E:\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2442, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5280)
  File "pandas\_libs\index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5126)
  File "pandas\_libs\hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20523)
  File "pandas\_libs\hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20477)
KeyError: 'datetime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/Quant/WebGrab/QueryTDX.py", line 114, in <module>
    get_tdx_history_day()
  File "E:/Quant/WebGrab/QueryTDX.py", line 71, in get_tdx_history_day
    data = api.get_k_data('600031', '2017-09-14', '2017-09-15')
  File "E:\Anaconda3\lib\site-packages\pytdx\hq.py", line 167, in get_k_data
    data['date'] = data['datetime'].apply(lambda x: x[0:10])
  File "E:\Anaconda3\lib\site-packages\pandas\core\frame.py", line 1964, in __getitem__
    return self._getitem_column(key)
  File "E:\Anaconda3\lib\site-packages\pandas\core\frame.py", line 1971, in _getitem_column
    return self._get_item_cache(key)
  File "E:\Anaconda3\lib\site-packages\pandas\core\generic.py", line 1645, in _get_item_cache
    values = self._data.get(item)
  File "E:\Anaconda3\lib\site-packages\pandas\core\internals.py", line 3590, in get
    loc = self.items.get_loc(item)
  File "E:\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2444, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5280)
  File "pandas\_libs\index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5126)
  File "pandas\_libs\hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20523)
  File "pandas\_libs\hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20477)
KeyError: 'datetime'

**Comment by yutiansut** [comment]
收到 好像是出错了  这个是早年版本 后来在QUANTAXIS里面改了忘了在这里更新了... @cafecai

**Comment by yutiansut** [comment]
已经修复 @cafecai  https://github.com/rainx/pytdx/pull/59

**Comment by yutiansut** [comment]
```powershell
In [1]: from pytdx.hq import TdxHq_API

In [2]: api=TdxHq_API()

In [3]: with api.connect():
   ...:     print(api.get_k_data('600031', '2017-09-14', '2017-09-15'))
   ...:
            open  close  high   low       vol       amount        date    code
date
2017-09-14  7.81   7.75  7.86  7.71  397598.0  308731776.0  2017-09-14  600031
2017-09-15  7.76   7.69  7.77  7.66  314262.0  241509184.0  2017-09-15  600031

```

**Comment by rainx** [comment]
已经 merge pr ..  1.43 版本
