### ISSUE TITLE
heartbeat抛出异常无处拦截

### ISSUE THREAD

**Issue by wuxin1030** [rainx/pytdx#68]
我发现有的时候心跳线程会抛出异常，但是因为此时并未执行任何操作，导致没有合适的地方进行拦截。能否把心跳改为不抛出任何异常？
等到下一次实际调用的时候，因为无法工作在抛出异常，也方便拦截。

**Comment by wuxin1030** [comment]
我看了源代码do_heartbeat确实有try。但是很奇怪，事实是。。。。。。  什么情况？
Exception in thread Thread-2:
Traceback (most recent call last):
  File "c:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\Anaconda3\lib\site-packages\pytdx\heartbeat.py", line 28, in run
    self.api.do_heartbeat()
  File "c:\Anaconda3\lib\site-packages\pytdx\hq.py", line 150, in do_heartbeat
    self.get_security_count(random.randint(0, 1))
  File "c:\Anaconda3\lib\site-packages\pytdx\base_socket_client.py", line 53, in
 wrapper
    ret = func(self, *args, **kw)
  File "c:\Anaconda3\lib\site-packages\pytdx\hq.py", line 76, in get_security_co
unt
    return cmd.call_api()
  File "c:\Anaconda3\lib\site-packages\pytdx\parser\base.py", line 64, in call_a
pi
    result = self._call_api()
  File "c:\Anaconda3\lib\site-packages\pytdx\parser\base.py", line 121, in _call
_api
    raise ResponseHeaderRecvFails("head_buf is not 0x10 : " + str(head_buf))
pytdx.parser.base.ResponseHeaderRecvFails: head_buf is not 0x10 : b''

**Comment by wuxin1030** [comment]
是否因为ResponseHeaderRecvFails异常继承自BaseException  
而拦截的是Exception，导致拦截不到。

**Comment by rainx** [comment]
有可能，我后面处理一下

**Comment by user20171001** [comment]
这个完全应该自己处理一下，pytdx的最主要功能应该是网络包的解析

**Comment by rainx** [comment]
@wuxin1030 pytdx-1.46 版本修复了一下，已经全部继承子Exception，请检验一下

**Comment by wuxin1030** [comment]
多谢 @rainx
